name: "Install PXT"
description: "Install PXT"
runs:
    using: "composite"
    steps:
      - run: "sudo apt-get install -y --quiet xvfb libudev-dev"
        shell: "bash"
      - run: "sudo yarn global add pxt"
        shell: "bash"